PROGRAM	=	main
OBJS	=	global_variable.o cross.o rotation.o complex.o solver_vec_radi.o main.o
SRCS	=	$(OBJS:%.o=%.c)
CC	=	gcc
CFLAGS	= -O3 -march=native
LDFLAGS	=

$(PROGRAM):$(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(PROGRAM) $(OBJS) $(LDLIBS) -lm
